http://localhost:3000
Authorization : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInVzZXJfaWQiOiIyMDIzMTIxMDExMTUyNDE4MyIsImlhdCI6MTcwMjIwODI3MywiZXhwIjoxNzAyNDY3NDczfQ.N8Jjz0s_2Oc029TNAC5Pu1JeRjxTXgTuQY1WvlIW3tU
Content-Type : Application/json
GET /dashboard
